# Site settings
title: inferentia
email: 
description: > # this means to ignore newlines until "baseurl:"
url: "http://inferentia.co.uk" # the base hostname & protocol for your site
twitter_username: gpinference
github_username:  inferentia

# Build settings
markdown: kramdown
